language: scala
jdk:
  - openjdk16
scala:
  - 3.0.0
services:
  - docker
before_install:
  - docker-compose up -d cassandra
before_script:
  - sleep 15  # give cassandra some time to startup
script:
  - sbt test