name: Build and test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Build
        run: sbt compile Test/compile
      - name: Test
        run: sbt test
